AdminUser.create!([
                    { email: "admin@example.com", password: "password",
encrypted_password: "$2a$12$jsNOrjFNFIRPH.sNlxAnJ.s3hvX/8bF783hVb2wt4HpFm5LJSIKz.",
reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil }
                  ])

TaxRateByLocation.create!([
                            { province:    "Manitoba",
                              current_gst: 5000,
                              current_hst: 0,
                              current_pst: 7000,
                              current_qst: 0 },
                            { province:    "Alberta",
                              current_gst: 5000,
                              current_hst: 0,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Saskatchewan",
                              current_gst: 5000,
                              current_hst: 0,
                              current_pst: 6000,
                              current_qst: 0 },
                            { province:    "British Columbia",
                              current_gst: 5000,
                              current_hst: 0,
                              current_pst: 7000,
                              current_qst: 0 },
                            { province:    "New Brunswick",
                              current_gst: 0,
                              current_hst: 15_000,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Newfoundland and Labrador",
                              current_gst: 0,
                              current_hst: 15_000,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Northwest Territories",
                              current_gst: 5000,
                              current_hst: 0,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Nova Scotia",
                              current_gst: 0,
                              current_hst: 15_000,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Nunavut",
                              current_gst: 5000,
                              current_hst: 0,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Ontario",
                              current_gst: 0,
                              current_hst: 13_000,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Prince Edward Island",
                              current_gst: 0,
                              current_hst: 15_000,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Yukon",
                              current_gst: 5000,
                              current_hst: 0,
                              current_pst: 0,
                              current_qst: 0 },
                            { province:    "Quebec",
                              current_gst: 8000,
                              current_hst: 0,
                              current_pst: 0,
                              current_qst: 9975 }
                          ])
ServiceType.create!([
                      { service_type_name: "Mentoring Session",
                        service_type_description: "A meeting to mentor someone on a specific
                        topic.", meeting_required: true },
                      { service_type_name:        "Map Making",
                        service_type_description: "This involves designing and drawing a map of
                        something, such as a local area or the interior of a structure.",
                        meeting_required:         false },
                      { service_type_name: "Optimization",
                        service_type_description: "This involves optimizing some aspect of your
                        TTRPG experience on a mechanical level.", meeting_required: false },
                      { service_type_name: "Research",
                        service_type_description: "Provide research on a specific topic related
                        to TTRPGs", meeting_required: false },
                      { service_type_name: "Teaching",
                        service_type_description: "Teaching someone how to do a specific thing
                          for TTRPGs.", meeting_required: true },
                      { service_type_name: "Artwork", service_type_description: "Making artwork.",
                        meeting_required: false },
                      { service_type_name: "Designing",
                    service_type_description: "Designing something related to TTRPGs. This can
                     involve designing player Species, Classes, Organizations, or designing
                     Encounters, Dungeons, and Monsters.", meeting_required: false },
                      { service_type_name: "Writing",
                    service_type_description: "Writing something for TTRPGs, typically related
                     to narrative. Could be NPC dialogue, overarching plots, character backstories,
                     etc etc.", meeting_required: false }
                    ])
OrderItemStatus.create!([
                          { status: "completed" },
                          { status: "in-progress" },
                          { status: "accepted" },
                          { status: "unpaid" },
                          { status: "cancelled" },
                          { status: "paid" }
                        ])

User.create!([
               { user_name: "Chris", password: "password", email: "chrissmithart@proton.me",
             description: "DM, Artist, Programmer.", address: "888 Mulvey Avenue",
             tax_rate_by_location: TaxRateByLocation.find(1),
             encrypted_password: "$2a$12$GTHi0aOZvH1Y9atCSU.t7e9bFYWfdQVsYRV5n8NqsGbpe6G6gmK9i",
             reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Zach", password: "password", email: "zmschuster@gmail.com",
             description: "Skater, Artist, fun guy, super tall.", address: "Somewhere...",
             tax_rate_by_location: TaxRateByLocation.find(3), encrypted_password: "password",
             reset_password_token: nil,
             reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Jordan", password: "password", email: "jpfinn@gmail.com",
             description: "Comic book writer, DM, Forgotten Realms is my favorite D&D setting.",
             address: "Someplace", tax_rate_by_location: TaxRateByLocation.find(11),
             encrypted_password: "$2a$12$9HZT0FrNa8TPHur1Us3mGumuaYKTFICeY3U5nsmSTo6kRQXD4PyP2",
             reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Andrew", password: "password", email: "abuttz@gmail.com",
             description: "Electrician, DM, Player, awesome person.", address: "Somewhere",
             tax_rate_by_location: TaxRateByLocation.find(1), encrypted_password: "password",
             reset_password_token: nil,
             reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Bill", password: "password", email: "willuprising@gmail.com",
             description: "Electrician, Player, has an epic beard.", address: "another place",
             tax_rate_by_location: TaxRateByLocation.find(1), encrypted_password: "password",
             reset_password_token: nil,
             reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Nick", password: "password", email: "nick@smith.com",
             description: "Chris's awesome brother", address: "123 Fake Street",
             tax_rate_by_location: TaxRateByLocation.find(1),
             encrypted_password: "$2a$12$1OKXo3EQh2pGKBwAGexW8.38vvpijz7VloB6IVOnLJtUPNpdXPwRS",
             reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Chrus Smoth", password: "password",
               email: "chrustacean69420@gmail.com",
             description: "something", address: "18 Atkinson Road",
             tax_rate_by_location: TaxRateByLocation.find(6),
             encrypted_password: "$2a$12$oGg3Davr86q6dk022F/GDuJ7ZRAAfxhg/K0orbYA1QhDKptYJFiPy",
             reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "BeetleMan", password: "password", email: "beetleman@gmail.com",
             description: "A big bug person", address: "123 Shell Street",
             tax_rate_by_location: TaxRateByLocation.find(3),
             encrypted_password: "$2a$12$26xrqANn2T3bc2/wtq6JuOaG10KjtaW8gRsoe3TBpC4nPX6wcFIWe",
             reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Jeff", password: "password", email: "jeff@jeff.com",
               description: "My name is Jeff",
             address: "123 Jeff Street", tax_rate_by_location: TaxRateByLocation.find(10),
             encrypted_password: "$2a$12$ObJ59WmAB36KfQlHnnwRCOzU5XD6P09Aa7xaFQIQLxP85TJ1XsOYK",
             reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil },
               { user_name: "Someone", password: "password", email: "someone123@gmail.com",
             description: "Someone Somewhere", address: "Somewhere 123 Street",
             tax_rate_by_location: TaxRateByLocation.find(6),
             encrypted_password: "$2a$12$7Ali8UO8xPzVtljj2v5nLOfBTVpWfUsCDw155U3qRhsLCuAb.87u.",
             reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil }
             ])

ActiveStorage::Blob.create!([
                              { key: "glnebaslcx5lvkq69clronhpyh6r", filename: "mask.png",
                              content_type: "image/png",
metadata: { "identified" => true, "width" => 336, "height" => 298, "analyzed" => true },
service_name: "amazon", byte_size: 75_338, checksum: "q54qaLy6CNy9e2BLZ0flIg==" },
                              { key: "923jdqsjcow8sq12wj4pi2ms9bi9", filename: "hero-man.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 780, "height" => 757,
                            "analyzed" => true }, service_name: "amazon", byte_size: 532_868,
                            checksum: "Qvl3bke3/tkEqqxA+1WBOQ==" },
                              { key: "2172vf3y8zks5vtjcdgetao5rexk", filename: "waterdeep.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 1619, "height" => 2508,
                            "analyzed" => true }, service_name: "amazon", byte_size: 2_522_992,
                            checksum: "Bu3j4Bus+leh16qfXvxuZg==" },
                              { key: "294jtxot6e828bkzsvf7pd9l0doh", filename: "WW-Link.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 328, "height" => 277,
                            "analyzed" => true }, service_name: "amazon", byte_size: 33_391,
                            checksum: "DS+kEoAD7yLI0gYIFQNsEg==" },
                              { key: "okf04yo95fiid75i5ule9m9vhi1h", filename: "discord.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 619, "height" => 470,
                            "analyzed" => true }, service_name: "amazon", byte_size: 10_386,
                            checksum: "10hl4QlPWsCg54KHVEn/Zg==" },
                              { key: "dxpx34ago5v7r0qy019iswm3kbf4", filename: "WW-Link.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 250, "height" => 211,
                            "analyzed" => true }, service_name: "amazon", byte_size: 21_275,
                            checksum: "lZzfHR4BI1lQl3cOU/igMA==" },
                              { key: "hcm9ht7z2j5sndrjuzfkdl5i3z89", filename: "discord.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 250, "height" => 190,
                            "analyzed" => true }, service_name: "amazon", byte_size: 5330,
                            checksum: "0eOl+XaJtEiT2AkedUka5w==" },
                              { key: "vbtptzhuuk3d8s8anu9i3jf0o2qt", filename: "mask.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 250, "height" => 222,
                            "analyzed" => true }, service_name: "amazon", byte_size: 69_616,
                            checksum: "0mQ2cd2MMtVyutW45yWVqg==" },
                              { key: "ylxrnyshylpjtzb9v67en4mjxnpk", filename: "hero-man.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 250, "height" => 243,
                            "analyzed" => true }, service_name: "amazon", byte_size: 85_454,
                            checksum: "i/pkLJnsiW1Jy/dusF2vRQ==" },
                              { key: "sjmlawyc0djcc4jddv1uhtxekln2", filename: "waterdeep.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 161, "height" => 250,
                            "analyzed" => true }, service_name: "amazon", byte_size: 59_341,
                            checksum: "5pU8kjQXVVf6xBaG2YD2JQ==" },
                              { key: "weh9qd0lc20g96k8a9wq8cpwj3gr", filename: "waterdeep.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 323, "height" => 500,
                            "analyzed" => true }, service_name: "amazon", byte_size: 192_069,
                            checksum: "h4BZoHvc+ulM0cx52ho6Iw==" },
                              { key: "7s422ayyoqmnfztped0pxgjlwacd", filename: "WW-Link.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 500, "height" => 422,
                            "analyzed" => true }, service_name: "amazon", byte_size: 50_459,
                            checksum: "nUw2BNx8K8Bwo59FejBGoA==" },
                              { key: "1ast3n9vrat118kfuxufa64n7sal", filename: "discord.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 500, "height" => 380,
                            "analyzed" => true }, service_name: "amazon", byte_size: 16_279,
                            checksum: "m3iKZg0rUd6LNbXFJbzmpA==" },
                              { key: "renzf2lfl5jlhp7ll2l6b5rffojt", filename: "mask.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 500, "height" => 443,
                            "analyzed" => true }, service_name: "amazon", byte_size: 209_682,
                            checksum: "tlcxx7ZvP5Xt4pvznd7AOg==" },
                              { key: "uhse62prkpunobg9uthqmbdglpew", filename: "hero-man.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 500, "height" => 485,
                            "analyzed" => true }, service_name: "amazon", byte_size: 261_108,
                            checksum: "0fDi0p3THU1rTQIR9M2s5w==" },
                              { key: "eulplj3fpxiocjuore1eebjlzn77", filename: "mask.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 100, "height" => 89,
                            "analyzed" => true }, service_name: "amazon", byte_size: 15_424,
                            checksum: "QAN0VCJ7OWW9HOC7mNAD6w==" },
                              { key: "80id9p47ow3clhhjkbqoct6hukz5", filename: "discord.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 100, "height" => 76,
                            "analyzed" => true }, service_name: "amazon", byte_size: 2720,
                            checksum: "JOFtjBLwfKD61hJfBj5pcQ==" },
                              { key: "dxy8powabbpuh2b0z3ui2exg5u7k", filename: "waterdeep.png",
                              content_type: "image/png",
                            metadata: { "identified" => true, "width" => 65, "height" => 100,
                            "analyzed" => true }, service_name: "amazon", byte_size: 12_845,
                            checksum: "Ca1VNTcNtXu0GG9wRNlaPw==" },
                              { key: "rshfza9gl40rdtopqsewdcpiitdf", filename: "WW-Link.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 100, "height" => 84,
                            "analyzed" => true }, service_name: "amazon", byte_size: 5898,
                            checksum: "LoFPwgx+0rzt/6IfC1C+MA==" },
                              { key: "kunqxqz8q9tf2itjn66uucmp09wp", filename: "hero-man.jpg",
                              content_type: "image/jpeg",
                            metadata: { "identified" => true, "width" => 100, "height" => 97,
                            "analyzed" => true }, service_name: "amazon", byte_size: 22_954,
                            checksum: "W4t0qgF55oYHCKqE+qtQdg==" }
                            ])

ActiveStorage::VariantRecord.create!([
                                       { blob_id:          4,
                                         variation_digest: "1MP3AY8ECyMYxzbysAPgEuDLmk4=" },
                                       { blob_id:          5,
                                         variation_digest: "kwyO3uzvkt+rcijHycD96q9j0ME=" },
                                       { blob_id:          1,
                                         variation_digest: "kwyO3uzvkt+rcijHycD96q9j0ME=" },
                                       { blob_id:          2,
                                         variation_digest: "1MP3AY8ECyMYxzbysAPgEuDLmk4=" },
                                       { blob_id:          3,
                                         variation_digest: "kwyO3uzvkt+rcijHycD96q9j0ME=" },
                                       { blob_id:          3,
                                         variation_digest: "Bwk2KnB+OXmuJ8AZwOWWxe3HQLc=" },
                                       { blob_id:          4,
                                         variation_digest: "9HYOcvhq8775Q8hxsZ+YtV4+l38=" },
                                       { blob_id:          5,
                                         variation_digest: "Bwk2KnB+OXmuJ8AZwOWWxe3HQLc=" },
                                       { blob_id:          1,
                                         variation_digest: "Bwk2KnB+OXmuJ8AZwOWWxe3HQLc=" },
                                       { blob_id:          2,
                                         variation_digest: "9HYOcvhq8775Q8hxsZ+YtV4+l38=" },
                                       { blob_id:          1,
                                         variation_digest: "kew+Jjn6rrgNk4/Pj4n+LM0hZVg=" },
                                       { blob_id:          5,
                                         variation_digest: "kew+Jjn6rrgNk4/Pj4n+LM0hZVg=" },
                                       { blob_id:          3,
                                         variation_digest: "kew+Jjn6rrgNk4/Pj4n+LM0hZVg=" },
                                       { blob_id:          4,
                                         variation_digest: "wj2EsykI81rCJCK6QU6D9xirR/c=" },
                                       { blob_id:          2,
                                         variation_digest: "wj2EsykI81rCJCK6QU6D9xirR/c=" }
                                     ])

ActiveStorage::Attachment.create!([
                                    { name: "image", record_type: "User", record_id: 1,
blob_id: 1 },
                                    { name: "image", record_type: "User", record_id: 2,
blob_id: 2 },
                                    { name: "image", record_type: "User", record_id: 3,
blob_id: 3 },
                                    { name: "image", record_type: "User", record_id: 4,
blob_id: 4 },
                                    { name: "image", record_type: "User", record_id: 5,
blob_id: 5 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 1, blob_id: 6 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 2, blob_id: 7 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 3, blob_id: 8 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 4, blob_id: 9 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 5, blob_id: 10 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 6, blob_id: 11 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 7, blob_id: 12 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 8, blob_id: 13 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 9, blob_id: 14 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 10, blob_id: 15 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 11, blob_id: 16 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 12, blob_id: 17 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 13, blob_id: 18 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 14, blob_id: 19 },
                                    { name: "image", record_type: "ActiveStorage::VariantRecord",
record_id: 15, blob_id: 20 }
                                  ])
ServiceOffer.create!([
                       { service_offer_name: "Boss Monster Design", service_offer_price: 500,
service_offer_notes: "Mentoring you on how to design Boss Monsters for your TTRPG games.",
google_forms_link: "google.com", caldotcom_link: "cal.com", slot_availabilty: 10,
user: User.find(1),
service_type: ServiceType.find(1) },
                       { service_offer_name: "Player Character Optimization (5e)",
                       service_offer_price: 600,
                     service_offer_notes: "I will optimize your 5th Edition D&D Character.
                     You will provide an idea and an already filled in character sheet and I will
                     provide you with a new character sheet that optimizes your character
                     mechanically.", google_forms_link: "google.com", caldotcom_link: "cal.com",
                     slot_availabilty: 10, user: User.find(2), service_type: ServiceType.find(3) },
                       { service_offer_name: "Local Area Map", service_offer_price: 1000,
                     service_offer_notes: "I will draw you a map of the local area for your
                     TTRPG game. You will provide me with written documents details what needs to
                     be in the map. I will provide you with a digital file of the map.",
                     google_forms_link: "google.com", caldotcom_link: "cal.com",
                     slot_availabilty: 6, user: User.find(1), service_type: ServiceType.find(2) },
                       { service_offer_name: "Dungeon Map", service_offer_price: 4500,
                     service_offer_notes: "I will draw you a map of a dungeon. You will provide
                      written documents regarding the layout of the dungeon, what is in the
                      various rooms. I will provide you with a series of image files for each floor
                      of the dungeon.", google_forms_link: "google.com", caldotcom_link: "cal.com",
                      slot_availabilty: 7, user: User.find(1), service_type: ServiceType.find(2) },
                       { service_offer_name: "City of Waterdeep Research", service_offer_price: 400,
                     service_offer_notes: "I will do research for you regarding something related
                      to the City of Waterdeep within the setting of Forgotten Realms. You will
                      provide me with questions you want answered, I will provide you with answers
                      to your questions.", google_forms_link: "google.com", caldotcom_link: "",
                      slot_availabilty: 9, user: User.find(3), service_type: ServiceType.find(4) },
                       { service_offer_name: "NPC Dialogue", service_offer_price: 500,
                     service_offer_notes: "I will write dialogue for an NPC for you. This can be
                     sample dialogue to help you practice roleplaying, or if you want the NPC to
                     make a speech or have someone overhear a conversation they are having. You will
                     provide me with details regarding the NPC and what, if any, scenes the
                     Dialogue is for. I will provide you with a document containing the text
                     for the dialogue (including notes).", google_forms_link: "google.com",
                      caldotcom_link: "", slot_availabilty: 8, user: User.find(3),
                      service_type: ServiceType.find(8) },
                       { service_offer_name: "Being a better player", service_offer_price: 100,
                     service_offer_notes: "Mentoring on how to be a better player at the table for
                     a TTRPG. This isn't about knowing mechanics or being tactical in combat.
                     These mentoring sessions are about being more polite, mindful, and a better
                     team player.", google_forms_link: "google.com", caldotcom_link: "cal.com",
                     slot_availabilty: 6, user: User.find(5), service_type: ServiceType.find(1) },
                       { service_offer_name: "Character Drawing", service_offer_price: 2500,
                     service_offer_notes: "I will draw your TTRPG character. This can be from any
                     setting (fantasy, sci-fi, cyberpunk, etc etc). You will provide me with
                     detailed information about who they are and what kind of pose you want
                     them to be in. Backgrounds are limited to a single colour (a transparent
                     background variant will be provided). I will provide you with some digital
                     images.", google_forms_link: "google.com", caldotcom_link: "",
                     slot_availabilty: 8, user: User.find(1), service_type: ServiceType.find(6) },
                       { service_offer_name: "How to play 5th Edition D&D",
                       service_offer_price: 1000,
                     service_offer_notes: "I will teach you how to play 5th edition Dungeons and
                     Dragons. I'll go over all the rules for how to run a player character.
                     This is a mechanics focused teaching session. Everything you should need to
                     know to get started will be encapsulated in one session.\r\nYou can provide
                     me with any background knowledge/history you have with TTRPGs.",
                     google_forms_link: "google.com", caldotcom_link: "cal.com",
                     slot_availabilty: 10, user: User.find(4), service_type: ServiceType.find(5) },
                       { service_offer_name: "Designs a Boss Encounter(5e)",
                       service_offer_price: 1500,
                     service_offer_notes: "I will design a Boss Encounter for you for 5th Edition
                     D&D. You will provide me with how many players you have and their
                     levels (you can also provide additional information about the
                     party if you want), you will provide me with a preference on what
                     kind of creature (Humanoid, Giant, Dragon, Elemental, etc etc) or you can
                     be specific and give me a specific creature you want a Boss Encounter
                     designed for (Beholder, Mindflayer, etc etc), and finally you will provide
                     me with a description of the boss encounter's location. I will return to you a
                     document with all the stats and abilities of this Boss and notes on how to
                     run the encounter.", google_forms_link: "google.com",
                     caldotcom_link: "cal.com", slot_availabilty: 10, user: User.find(4),
                     service_type: ServiceType.find(7) }
                     ])
